[tool.poetry]
name = "dunk"
version = "0.1.0"
description = ""
authors = ["Darren Burns <darrenb900@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
unidiff = "^0.7.3"
rich = "^12.0.1"
patch = "^1.16"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
